name: CI

on:
  schedule: 
    - cron: "0 17 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ${{runner.workspace}}/test_suite
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download SBML models, generate SED-ML, generate OMEX archive, run the simulation, genrate the comparison report
      working-directory: ${{runner.workspace}}/test_suite
      run: |
        PYTHONPATH=$(pwd) python report_generation/core.py

    - name: 'Upload Report'
      uses: actions/upload-artifact@v2
      with:
        name: comparison_report
        path: report.txt

