name: CI

on:
  schedule: 
    - cron: "30 1 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies and run simulations
      working-directory: ${{runner.workspace}}/test_suite
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        PYTHONPATH=$(pwd) python report_generation/core.py
        
    # Archiving results, logs, report
    - name: 'Archive results, logs, report'
      working-directory: ${{runner.workspace}}/test_suite
      run: |
        zip -r artifact_"`date +"%d_%m_%Y"`".zip report_generation/files/logs report_generation/files/results report.txt
        ls

    - name: Get artifact file name
      id: date
      run: echo ::set-output name=format::$(date +"%d_%m_%Y")

    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: artifact_${{steps.date.outputs.format}}
        path: artifact_${{steps.date.outputs.format}}.zip
        if-no-files-found: warn

