name: CI

on: [push]
  # schedule: 
  #   - cron: "30 23 * * 0"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies and run simulations
      working-directory: ${{runner.workspace}}/test_suite
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        PYTHONPATH=$(pwd) python report_generation/core.py
        
    # Archiving results, logs, report
    - name: 'Archive results, logs, report'
      working-directory: ${{runner.workspace}}/test_suite
      run: |
        now=$(date+"%m_%d_%Y")
        zip -r artifact_$now.zip report_generation/files/logs report_generation/files/results report.txt
      if-no-files-found: warn
    
    - name: 'Upload artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: comparison_report
        path: artifact_`date +'%m_%d_%Y'`.zip

